---
title: "Repo Template"
author: "**Repo Manager:** Adam Shelton <br />"
date: "`r paste('**Last updated:**', format(Sys.time(), '%B %d, %Y'))`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview
This repo is a template that is used to create new repos on the N3 GitHub org. It includes a .gitignore file that should prevent data files and other unnecessary files from being pushed to a repo, and a README template in both raw Markdown and R Markdown formats. If you **are not** using R delete the R Markdown template. Edit the README to add the appropriate title, Repo Manager and, other content. The R Markdown README will automatically put the current date in `full_month_name day, year` format when knitted. If you are not using R make sure to update the date as you update the repo.

This Overview section should be used to give a brief abstract of your project.

## Documents and Reports

If you have any important documents or reports you want people to view make sure to put them here.

## Methodology

Briefly describe the most essential parts of your methodology, making sure to include the names of datasets that were used and a link or reference to any external datasets. Also, include a description of any code or scripts you need to run the project, any order they should be run on, and any unusual dependencies, quirks, or features you think others should know about. 

## Table of Contents
A linked table of contents for all the files on the repo (you *do not* need to include the README and .gitignore files in this TOC)

Use the following format:

- **[A top level folder]() :** *a description of this folder (if necessary)*
  - **[A second level folder]()**
    - **[A file]() :** *a description of this file (required)*
- **[A top level file]() :** *a description of this file (required)*

## References

No one likes plagiarizers, cite your work!