name: Add actions from `repo-template`
on:
  push:
    branches:
      - main

jobs:
  add-actions:
    if: github.repository != 'n3-initiative/repo-template'
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.ANDY_BOT_PAT }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ANDY_BOT_PAT }}
          fetch-depth: 0

      - name: Set `git` identity
        run: |
          git config --global user.email "93400629+andy-bot-3000@users.noreply.github.com"
          git config --global user.name "andy-bot[bot]"

      - name: Merge changes from `repo-template`
        run: |
          git remote add -f repo-template "https://${{ secrets.ANDY_BOT_PAT }}:x-oauth-basic@github.com/n3-initiative/repo-template.git"
          git remote -v # list all added remotes
          git fetch --all
          if [[ $(git ls-remote origin add-actions) ]]; then
            echo "Update branch found on remote, checking out..."
            git checkout -t origin/add-actions
          else
            echo "No update branch found on remote, creating..."
            git checkout -b add-actions
          fi
          git merge -X ours --allow-unrelated-histories repo-template/main
          git rm --ignore-unmatch .github/workflows/add-actions.yaml
          git commit -a -m "Remove temp `add-actions` file"
          if [[ $(git diff main...add-actions) ]]; then
            echo "Changes found in repo-template, pushing to remote..."
            echo "OPEN_PR=true" >> "$GITHUB_ENV"
          else
            echo "There are no changes on repo-template, exiting..."
            echo "OPEN_PR=false" >> "$GITHUB_ENV"
            exit 0
          fi
          git remote set-url origin "https://x-access-token:${{ secrets.ANDY_BOT_PAT }}@github.com/${{ github.repository }}"
          git push --set-upstream origin add-actions

      - name: Create pull request
        uses: vsoch/pull-request-action@master
        if: env.OPEN_PR == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.ANDY_BOT_PAT }}
          BRANCH_PREFIX: "add-actions"
          PULL_REQUEST_FROM_BRANCH: "add-actions"
          PULL_REQUEST_TITLE: "Add GitHub Actions from `repo-template`"
          PASS_IF_EXISTS: TRUE
          PULL_REQUEST_UPDATE: TRUE
