on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  auto-request-review:
    name: Automatic Review Request
    runs-on: ubuntu-latest
    steps:
      - name: Request review
        uses: necojackarc/auto-request-review@v0.7.0
        with:
          token: ${{ secrets.ANDY_BOT_PAT }}
          config: .github/reviewers.yml # Config file location override
