on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Check variable names

jobs:
  check-var-names:
    runs-on: ubuntu-latest
    container: python:3
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
        # ag won't output if the following shell config isn't used
        # this is due to the way it prints colored text to stdout
        # this does not work locally with act
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt update
          apt install silversearcher-ag -y

      - name: Prepare files
        run: |
          python '.github/var_scan_cleaning.py'
        # ^ we need to remove named arguments from files
        # so they aren't flagged

      - name: Check variable names
        run: |
          chmod u+x '.github/var_scan.sh'
          bash '.github/var_scan.sh'
