on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Check variable names

jobs:
  check-var-names:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install silversearcher-ag -y
      - name: Check variable names
        run: |
          chmod u+x '.github/var_scan.sh'
          bash '.github/var_scan.sh'
