on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Check code to comment ratio

jobs:
  comment-ratio:
    runs-on: ubuntu-latest
    container: python:3
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install pandas tabulate
          apt update
          apt install cloc -y

      - name: Calculate comment to code ratio
        run: |
          cloc --vcs='git' --exclude-dir=,.github,renv,venv --exclude-lang=Markdown -by-percent='cm' --json . |
          python '.github/comment_ratio.py'
