on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Lint project

jobs:
  lint-project:
    runs-on: ubuntu-latest
    container: rocker/verse
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    path: /
    steps:
      - uses: actions/checkout@v2

      # - uses: r-lib/actions/setup-r@v1

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("lintr", "magrittr", "stringr"))'

      - name: Lint project directory
        run: |
          Rscript '.github/lint_r_files.R'

      - name: Linting results
        run: |
          if [ -f ".github/linting_fail" ]; then
            echo "Some tests failed"
            exit 1
          else
            echo "All tests passed"
            exit 0
          fi

      # - uses: actions-ecosystem/action-regex-match@v2
      #   id: regex-match
      #   name: Check variable names
      #   with:
      #     text: ${{ github.event.comment.body }}
      #     regex: '^( |\t)*(\w|data) *(=|<-).*$'
      #
      # - uses: actions-ecosystem/action-add-labels@v1
      #   if: ${{ steps.regex-match.outputs.match != '' }}
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     labels: ${{ steps.regex-match.outputs.group1 }}
