on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Lint project

jobs:
  lint-project:
    runs-on: ubuntu-latest
    container: rocker/verse
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("lintr"))'
          apt update
          apt install silversearcher-ag

      - name: Lint R files
        run: |
          Rscript '.github/lint_r_files.R'

      - name: Check variable names
        run: |
          chmod u+x '.github/var_scan.sh'
          bash '.github/var_scan.sh'

      - name: Linting results
        run: |
          if [ -f ".github/linting_fail" ]; then
            echo "Some tests failed"
            exit 1
          else
            echo "All tests passed"
            exit 0
          fi
      #
      # - uses: actions-ecosystem/action-add-labels@v1
      #   if: ${{ steps.regex-match.outputs.match != '' }}
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     labels: ${{ steps.regex-match.outputs.group1 }}
