on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Lint project

jobs:
  lint-project:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install lintr
        run: install.packages("lintr")
        shell: Rscript {0}

      - name: Lint project directory
        run: lintr::lint_dir()
        shell: Rscript {0}
      
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        name: Check variable names
        with:
          text: ${{ github.event.comment.body }}
          regex: '^( |\t)*(\w|data) *(=|<-).*$'

      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.regex-match.outputs.group1 }}