on: push

name: Lint project - R

jobs:
  lint-r:
    runs-on: ubuntu-latest
    container: rocker/verse
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("lintr"))'

      - name: Lint R files
        run: |
          Rscript '.github/lint_r_files.R'
